server:
  servlet:
    encoding:
      force: 'true'
      charset: UTF-8
  port: '8300'
spring:
  application:
    name: sensor-data
  profiles:
    active: prod
  redis:
    host: 133.186.241.167
    password: '*N2vya7H@muDTwdNMR!'
    database: 264
    port: 6379
springdoc:
  default-produces-media-type: application/json
  show-actuator: 'true'
  swagger-ui:
    disable-swagger-default-url: 'true'
    groups-order: desc
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: 'true'
  api-docs:
    path: /api-docs
  paths-to-match: /api/**
influxdb:
  bucket: TxT
  token: bfu66OESWmsehUar6VEfABaKLr4RwOklA8ll78l9LRCQWn2DfsTGGcnLVwpVO8H5MFX1jjp3AKGGwrVWC1Wiiw==
  url: http://146.56.98.218:8086
  org: TXT
eureka:
  client:
    fetch-registry: 'true'
    register-with-eureka: 'true'
management:
  endpoints:
    web:
      exposure:
        include: beans, conditions, configprops, env, health, httpexchanges, info, loggers, metrics, mappings, threaddump, shutdown
      base-path: /sensor-data-api-server/manage
  endpoint:
    health:
      show-details: always
