### co2 단일 데이터
GET localhost:8300/api/sensor/co2?place=class_a

### co2 단일 데이터
GET localhost:8300/api/sensor/co2?place=class_b

### co2 일간 데이터
GET localhost:8300/api/sensor/co2/day?place=class_a

### co2 일간 데이터
GET localhost:8300/api/sensor/co2/day?place=class_b

### co2 일간 시간별 평균 데이터
GET localhost:8300/api/sensor/co2/day-mean?place=class_a

### co2 일간 시간별 평균 데이터
GET localhost:8300/api/sensor/co2/day-mean?place=class_b

### co2 주간 데이터
GET localhost:8300/api/sensor/co2/week?place=class_a

### co2 주간 데이터
GET localhost:8300/api/sensor/co2/week?place=class_b

### co2 월간 데이터
GET localhost:8300/api/sensor/co2/month?place=class_a

### co2 월간 데이터
GET localhost:8300/api/sensor/co2/month?place=class_b
