### co2 단일 데이터
GET localhost:8300/api/sensor/co2

### co2 일간 데이터
GET localhost:8300/api/sensor/co2/day

### co2 주간 데이터
GET localhost:8300/api/sensor/co2/week

### co2 월간 데이터
GET localhost:8300/api/sensor/co2/month
