### 습도 단일 데이터
GET localhost:8300/api/sensor/humidity

### 습도 일간 데이터
GET localhost:8300/api/sensor/humidity/day

### 습도 주간 데이터
GET localhost:8300/api/sensor/humidity/week

### 습도 월간 데이터
GET localhost:8300/api/sensor/humidity/month
