### 단일 데이터
GET localhost:8300/api/sensor/humidity

### 일간 데이터
GET localhost:8300/api/sensor/humidity/day

### 주간 데이터
GET localhost:8300/api/sensor/humidity/week

### 월간 데이터
GET localhost:8300/api/sensor/humidity/month
