### 조도 단일 조회
GET http://localhost:8300/api/sensor/illumination

### 조도 일별 조회
GET http://localhost:8300/api/sensor/illumination/day

### 조도 주별 조회
GET http://localhost:8300/api/sensor/illumination/week

### 조도 월별 조회
GET http://localhost:8300/api/sensor/illumination/month