### 온도 단일 조회
GET http://localhost:8300/api/sensor/temperature

### 온도 일별 조회
GET http://localhost:8300/api/sensor/temperature/day

### 온도 주별 조회
GET http://localhost:8300/api/sensor/temperature/week

### 온도 월별 조회
GET http://localhost:8300/api/sensor/temperature/month